services:
  app:
    build: .
    volumes:
      - ./downloaded_data:/downloaded_data
      - ./output:/output
      - ./config:/config  # If you have config files

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./output:/output:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
