services:
  app:
    build: .
    volumes:
      - ./data:/data
      - ./output:/output
      - ./config:/config
    networks:
      - app_network
    restart: "no"

  nginx:
    image: nginx:alpine
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./output:/output
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app_network
    depends_on:
      - app

networks:
  app_network:
    driver: bridge
